### ISSUE TITLE
数据集缺失

### ISSUE THREAD

**Issue by Drew-youngking** [thuiar/CTMWA#1]
作者您好，请问MVSA的.pkl文件如何获取？
![0( J$TC1ZU5C7ER1$D7SA)V](https://github.com/user-attachments/assets/aebbdadc-e7ea-4ce6-ba87-d9254006f853)

**Comment by lj666534** [comment]
你好你是怎么解决的呀

**Comment by aakkaa0413** [comment]
怎么解决的啊哥

**Comment by ansucatherine** [comment]
您好，请问这个问题是怎么解决的呢？
